// Copies the frozen contract ABIs (contract/abi/*.json) into src/abi/*.ts as `as const` arrays.
// Usage: bun scripts/sync-abi.ts [check]. Never hand-edit the generated files.
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

export const ABI_NAMES = [
  'IAUSD',
  'ICoverManager',
  'ICoverVault',
  'IGaplessAccount',
  'IGaplessCreSink',
  'IGaplessFactory',
  'IGaplessInherited',
  'IPerplErrors',
  'IPerplMin'
] as const;

const ROOT = resolve(dirname(new URL(import.meta.url).pathname), '..');
export const SOURCE_DIR = resolve(ROOT, '../contract/abi');
export const TARGET_DIR = join(ROOT, 'src/abi');

export function render(name: string, json: string): string {
  const abi: unknown = JSON.parse(json);
  if (!Array.isArray(abi)) throw new Error(`${name}.json is not an ABI array`);
  return [
    `// Generated by scripts/sync-abi.ts from contract/abi/${name}.json. Do not edit.`,
    `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;`,
    ''
  ].join('\n');
}

export function renderIndex(): string {
  return [
    '// Generated by scripts/sync-abi.ts. Do not edit.',
    ...ABI_NAMES.map((n) => `export { ${n}Abi } from './${n}.ts';`),
    ''
  ].join('\n');
}

/** Returns the files whose content differs from the generated output. */
export function sync(check: boolean): string[] {
  const expected = new Map<string, string>();
  for (const name of ABI_NAMES) {
    expected.set(`${name}.ts`, render(name, readFileSync(join(SOURCE_DIR, `${name}.json`), 'utf8')));
  }
  expected.set('index.ts', renderIndex());
  const stale: string[] = [];
  if (!check) mkdirSync(TARGET_DIR, { recursive: true });
  for (const [file, content] of expected) {
    const path = join(TARGET_DIR, file);
    const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
    if (current === content) continue;
    stale.push(file);
    if (!check) writeFileSync(path, content);
  }
  if (existsSync(TARGET_DIR)) {
    for (const f of readdirSync(TARGET_DIR)) if (!expected.has(f)) stale.push(`${f} (not generated)`);
  }
  return stale;
}

if (import.meta.main) {
  const check = process.argv.slice(2).includes('check');
  const stale = sync(check);
  if (check && stale.length > 0) {
    process.stderr.write(`ABI out of sync: ${stale.join(', ')}. Run bun scripts/sync-abi.ts\n`);
    process.exit(1);
  }
  process.stdout.write(check ? 'ABIs in sync\n' : `synced ${ABI_NAMES.length} ABIs (${stale.length} changed)\n`);
}
