// Generated by scripts/sync-abi.ts from contract/abi/IPerplMin.json. Do not edit.
export const IPerplMinAbi = [
  {
    "type": "function",
    "name": "createAccount",
    "inputs": [
      {
        "name": "amountCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "depositCollateral",
    "inputs": [
      {
        "name": "amountCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "execOrder",
    "inputs": [
      {
        "name": "orderDesc",
        "type": "tuple",
        "internalType": "struct IPerplMin.OrderDesc",
        "components": [
          {
            "name": "orderDescId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiryBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "fillOrKill",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "immediateOrCancel",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "maxMatches",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverageHdths",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastExecutionBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxNegPnlCollatBPS",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "signature",
        "type": "tuple",
        "internalType": "struct IPerplMin.OrderSignature",
        "components": [
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "execOrderV2",
    "inputs": [
      {
        "name": "orderDesc",
        "type": "tuple",
        "internalType": "struct IPerplMin.OrderDesc",
        "components": [
          {
            "name": "orderDescId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiryBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "fillOrKill",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "immediateOrCancel",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "maxMatches",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverageHdths",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastExecutionBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxNegPnlCollatBPS",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "extension",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "signature",
        "type": "tuple",
        "internalType": "struct IPerplMin.OrderSignature",
        "components": [
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "execOrders",
    "inputs": [
      {
        "name": "orderDescs",
        "type": "tuple[]",
        "internalType": "struct IPerplMin.OrderDesc[]",
        "components": [
          {
            "name": "orderDescId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiryBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "postOnly",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "fillOrKill",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "immediateOrCancel",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "maxMatches",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "leverageHdths",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastExecutionBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "amountCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxNegPnlCollatBPS",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      },
      {
        "name": "revertOnFail",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [
      {
        "name": "signatures",
        "type": "tuple[]",
        "internalType": "struct IPerplMin.OrderSignature[]",
        "components": [
          {
            "name": "perpId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "orderId",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAccountByAddr",
    "inputs": [
      {
        "name": "accountAddress",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "accountInfo",
        "type": "tuple",
        "internalType": "struct IPerplMin.AccountInfo",
        "components": [
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "balanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockedBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "frozen",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "accountAddr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "positions",
            "type": "tuple",
            "internalType": "struct IPerplMin.PositionBitMap",
            "components": [
              {
                "name": "bank1",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank2",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank3",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank4",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAccountById",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "accountInfo",
        "type": "tuple",
        "internalType": "struct IPerplMin.AccountInfo",
        "components": [
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "balanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lockedBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "frozen",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "accountAddr",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "positions",
            "type": "tuple",
            "internalType": "struct IPerplMin.PositionBitMap",
            "components": [
              {
                "name": "bank1",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank2",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank3",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "bank4",
                "type": "uint256",
                "internalType": "uint256"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAccountFeeTier",
    "inputs": [
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "tier",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getContractVersion",
    "inputs": [],
    "outputs": [
      {
        "name": "major",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "minor",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "patch",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getFundingInterval",
    "inputs": [],
    "outputs": [
      {
        "name": "fundingInterval",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "getMinAccountOpenCNS",
    "inputs": [],
    "outputs": [
      {
        "name": "minAccountOpenCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getNextPriceAboveWithOrders",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "priceONS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "priceAboveONS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getNextPriceBelowWithOrders",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "priceONS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "priceBelowONS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPerpFeeSchedule",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "feeSchedId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "takerFeesPer100K",
        "type": "uint256[8]",
        "internalType": "uint256[8]"
      },
      {
        "name": "makerFeesPer100K",
        "type": "uint256[8]",
        "internalType": "uint256[8]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPerpetualInfo",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "perpetualInfo",
        "type": "tuple",
        "internalType": "struct IPerplMin.PerpetualInfo",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "symbol",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "priceDecimals",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotDecimals",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "linkFeedId",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "priceTolPer100K",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "marginTol",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "marginTolDecimals",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "refPriceMaxAgeSec",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "positionBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "insuranceBalanceCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "markPNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "markTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastPNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lastTimestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oraclePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "oracleTimestampSec",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "longOpenInterestLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "shortOpenInterestLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fundingStartBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "fundingRatePct100k",
            "type": "int16",
            "internalType": "int16"
          },
          {
            "name": "absFundingClampPctPer100K",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "basePricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxBidPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minBidPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxAskPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minAskPriceONS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "numOrders",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "ignOracle",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPosition",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "accountId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "positionInfo",
        "type": "tuple",
        "internalType": "struct IPerplMin.PositionInfo",
        "components": [
          {
            "name": "accountId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "nextNodeId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "prevNodeId",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "positionType",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "depositCNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pricePNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "lotLNS",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "entryBlock",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "pnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "deltaPnlCNS",
            "type": "int256",
            "internalType": "int256"
          },
          {
            "name": "premiumPnlCNS",
            "type": "int256",
            "internalType": "int256"
          }
        ]
      },
      {
        "name": "markPricePNS",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "markPriceValid",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getTakerFee",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getVolumeAtBookPrice",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "priceONS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "bids",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expBids",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "asks",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expAsks",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getWithdrawAllowanceData",
    "inputs": [
      {
        "name": "blockNumber",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "allowanceCNS",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "expiryBlock",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "lastAllowanceBlock",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "cnsPerBlock",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "increasePositionCollateral",
    "inputs": [
      {
        "name": "perpId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "amountCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "isHalted",
    "inputs": [],
    "outputs": [
      {
        "name": "halted",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "whitelisted",
    "inputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "whitelistingEnabled",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "withdrawCollateral",
    "inputs": [
      {
        "name": "amountCNS",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  }
] as const;
