// Generated by scripts/sync-abi.ts from deployments/143.json. Do not edit.
export const CHAIN_ID = 143
export const DEPLOY_BLOCK = 111101834n
export const LISTED_PERP_ID = 1

export const ADDRESSES = {
  CoverManager: '0xb07C20cb5328d5208A1453521b94beeB3Faa1771',
  CoverVault: '0xab3CB7b3b28366eD7f6C59DbD2D708890919B289',
  GaplessFactory: '0xB1a255e9D4CEdC20998ddC67a7Ec5e0B71bd8777',
  PerplExchange: '0x34B6552d57a35a1D042CcAe1951BD1C370112a6F',
  AUSD: '0x00000000eFE302BEAA2b3e6e1b18d08D69a9012a',
} as const
