// Generated by scripts/sync-abi.ts from deployments/143.json. Do not edit.
export const DEPLOYMENT = {
  chainId: 143,
  CoverManager: "0xb07C20cb5328d5208A1453521b94beeB3Faa1771" as `0x${string}` | null,
  GaplessFactory: "0xB1a255e9D4CEdC20998ddC67a7Ec5e0B71bd8777" as `0x${string}` | null,
} as const;
