/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as ProofRouteImport } from './routes/proof'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GapIndexRouteImport } from './routes/gap-index'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAgentRouteImport } from './routes/settings/agent'
import { Route as CoversCoverIdRouteImport } from './routes/covers/$coverId'

const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofRoute = ProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GapIndexRoute = GapIndexRouteImport.update({
  id: '/gap-index',
  path: '/gap-index',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAgentRoute = SettingsAgentRouteImport.update({
  id: '/settings/agent',
  path: '/settings/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const CoversCoverIdRoute = CoversCoverIdRouteImport.update({
  id: '/covers/$coverId',
  path: '/covers/$coverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gap-index': typeof GapIndexRoute
  '/home': typeof HomeRoute
  '/onboard': typeof OnboardRoute
  '/proof': typeof ProofRoute
  '/stats': typeof StatsRoute
  '/trade': typeof TradeRoute
  '/vault': typeof VaultRoute
  '/covers/$coverId': typeof CoversCoverIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gap-index': typeof GapIndexRoute
  '/home': typeof HomeRoute
  '/onboard': typeof OnboardRoute
  '/proof': typeof ProofRoute
  '/stats': typeof StatsRoute
  '/trade': typeof TradeRoute
  '/vault': typeof VaultRoute
  '/covers/$coverId': typeof CoversCoverIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gap-index': typeof GapIndexRoute
  '/home': typeof HomeRoute
  '/onboard': typeof OnboardRoute
  '/proof': typeof ProofRoute
  '/stats': typeof StatsRoute
  '/trade': typeof TradeRoute
  '/vault': typeof VaultRoute
  '/covers/$coverId': typeof CoversCoverIdRoute
  '/settings/agent': typeof SettingsAgentRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gap-index'
    | '/home'
    | '/onboard'
    | '/proof'
    | '/stats'
    | '/trade'
    | '/vault'
    | '/covers/$coverId'
    | '/settings/agent'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gap-index'
    | '/home'
    | '/onboard'
    | '/proof'
    | '/stats'
    | '/trade'
    | '/vault'
    | '/covers/$coverId'
    | '/settings/agent'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/gap-index'
    | '/home'
    | '/onboard'
    | '/proof'
    | '/stats'
    | '/trade'
    | '/vault'
    | '/covers/$coverId'
    | '/settings/agent'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GapIndexRoute: typeof GapIndexRoute
  HomeRoute: typeof HomeRoute
  OnboardRoute: typeof OnboardRoute
  ProofRoute: typeof ProofRoute
  StatsRoute: typeof StatsRoute
  TradeRoute: typeof TradeRoute
  VaultRoute: typeof VaultRoute
  CoversCoverIdRoute: typeof CoversCoverIdRoute
  SettingsAgentRoute: typeof SettingsAgentRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof': {
      id: '/proof'
      path: '/proof'
      fullPath: '/proof'
      preLoaderRoute: typeof ProofRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gap-index': {
      id: '/gap-index'
      path: '/gap-index'
      fullPath: '/gap-index'
      preLoaderRoute: typeof GapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/agent': {
      id: '/settings/agent'
      path: '/settings/agent'
      fullPath: '/settings/agent'
      preLoaderRoute: typeof SettingsAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/covers/$coverId': {
      id: '/covers/$coverId'
      path: '/covers/$coverId'
      fullPath: '/covers/$coverId'
      preLoaderRoute: typeof CoversCoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GapIndexRoute: GapIndexRoute,
  HomeRoute: HomeRoute,
  OnboardRoute: OnboardRoute,
  ProofRoute: ProofRoute,
  StatsRoute: StatsRoute,
  TradeRoute: TradeRoute,
  VaultRoute: VaultRoute,
  CoversCoverIdRoute: CoversCoverIdRoute,
  SettingsAgentRoute: SettingsAgentRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
