//  @ts-check

import { globalIgnores } from 'eslint/config'
import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  // Generated by scripts/sync-abi.ts; eslint --fix would fail its CI check.
  globalIgnores(['src/abi/', 'src/config/addresses.143.ts']),
  ...tanstackConfig,
]
